buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:1.2-SNAPSHOT'
    }
}

apply plugin: 'forge'

version = "1.0.0-mc1.7.10"
group = "com.steve.ai"
archivesBaseName = "steve-ai-mod"

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "run"
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    // HTTP client for LLM API calls
    compile 'org.apache.httpcomponents:httpclient:4.5.14'
    compile 'org.apache.httpcomponents:httpcore:4.4.16'
    
    // Gson is already included in Minecraft, but we declare it for clarity
    // compile 'com.google.code.gson:gson:2.8.9'
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.0'
}
