modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="vasyan"
version="1.0.0"
displayName="Vasyan AI mod"
description='''
AI-controlled Vasyan entities that follow natural language commands,
mine resources, build structures, and behave like real players.
'''
authors="Iosif Pravets"
displayURL="https://github.com/pravets/Vasyan"

[[dependencies.vasyan]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vasyan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

